# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unidown/plugins/data/protobuf/plugin_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unidown/plugins/data/protobuf/plugin_info.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n/unidown/plugins/data/protobuf/plugin_info.proto\">\n\x0fPluginInfoProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\tb\x06proto3')
)




_PLUGININFOPROTO = _descriptor.Descriptor(
  name='PluginInfoProto',
  full_name='PluginInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PluginInfoProto.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='PluginInfoProto.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='PluginInfoProto.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['PluginInfoProto'] = _PLUGININFOPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PluginInfoProto = _reflection.GeneratedProtocolMessageType('PluginInfoProto', (_message.Message,), dict(
  DESCRIPTOR = _PLUGININFOPROTO,
  __module__ = 'unidown.plugins.data.protobuf.plugin_info_pb2'
  # @@protoc_insertion_point(class_scope:PluginInfoProto)
  ))
_sym_db.RegisterMessage(PluginInfoProto)


# @@protoc_insertion_point(module_scope)
